### ISSUE TITLE
Add new commands for DB management

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/tripaldock#15]
It would be cool to have:
```
./tripaldock pg_dump
./tripaldock psql
./tripaldock pg_restore
```

**Comment by bradfordcondon** [comment]
I dont know if this counts as the same issue, but adding to this: I think we want to supply PSQL dumps that include chado with ontologies loaded, and chado with teh devseed dataset loaded.  When installing ./tripaldock it should be clear how to load these (if we decide to not integrate it, then we should link to the dumps in the docks and give example setup commands)

**Comment by almasaeed2010** [comment]
DB commands added.

I'll create a new issue for a seeded database option.
