### ISSUE TITLE
running jobs via tripaldock doesnt work?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripaldock#19]
```
./tripaldock drush trp-run-jobs --username=tripal --root=/var/www/html

TRIPALDOCK: Running drush trp-run-jobs --username=tripal --root=/var/www/html
2018-02-10 20:19:07
ERROR: Please provide a username (--username argument) for running this job.
Drush command terminated abnormally due to an unrecoverable error.
```

**Comment by almasaeed2010** [comment]
Need to find a way to pass the entire command. Apparently it is passing arguments but not options.

**Comment by bradfordcondon** [comment]
I think I need more shell experience before i can fix this, but https://stackoverflow.com/questions/12314451/accessing-bash-command-line-args-vs looks like a good place to start

**Comment by almasaeed2010** [comment]
Should be fixed but a test would be nice! I'll push a new release so composer update can work.
