### ISSUE TITLE
can machines boot with more memory allocated?

### ISSUE THREAD

**Issue by bradfordcondon** [statonlab/tripaldock#48]
php.ini is set for 128M.  abdullah suggests .5G as a minimum for running a tripal site without running into mem issues.

**Comment by almasaeed2010** [comment]
The obo loader can get up to a nice round 1G so we might wanna account for that.

**Comment by almasaeed2010** [comment]
See new environment variable in `docker-compose.yaml` (branch fixes)

Thanks!
