### ISSUE TITLE
tripaldock new site_name failed

### ISSUE THREAD

**Issue by NicHerndon** [statonlab/tripaldock#55]
I ran the following commands (the output from all but last one is not included), and got a **command not found** error.
```
$ git clone https://github.com/statonlab/tripaldock.git
$ composer global require statonlab/tripaldock:~0.1.1
$ cd tripaldock/
$ ./tripaldock new tripal_dev

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Command\Command' not found in tripaldock/src/NewCommand.php:12
Stack trace:
#0 tripaldock/src/bootstrap.php(9): require()
#1 tripaldock/tripaldock(19): require('/Users/herndonn...')
#2 {main}
  thrown in tripaldock/src/NewCommand.php on line 12
```

**Comment by almasaeed2010** [comment]
Hello Nic

You don’t need to clone the repo. All you need is to install tripaldock globally using composer. This article explains how to make global modules available: https://akrabat.com/global-installation-of-php-tools-with-composer/

Let me know if anything is not clear

**Comment by NicHerndon** [comment]
That worked. I have a Tripal instance running - very cool. Thank you.

**Comment by almasaeed2010** [comment]
Great!
